### ISSUE TITLE
 distance problem

### ISSUE THREAD

**Issue by SzentiX** [Xilophinum/posters#6]
Is there option to get longer distance to see photo?

**Comment by FripeX** [comment]
> Is there option to get longer distance to see photo?

Create a config file and put
`Config = {}`
`Config.ViewDistance = 120.0`

Then go to the client and replace this 

> CreateThread(function()
>     while true do
>         local sleep = 1500
>         for k,v in pairs(ActivePosters) do
>             if #(GLOBAL_COORDS - v.pointA) < 50.0 or #(GLOBAL_COORDS - v.pointB) < 50.0 then
>                 sleep = 0
>                 DrawImageOnArea(v.pointA, v.pointB, v.pointB.z, v.pointA.z, 255, 255, 255, 255, v.textureid, v.txn)
>             end
>         end
>         Wait(sleep)
>     end
> end)

by this : 

> CreateThread(function()
>     while true do
>         local sleep = 1500
>         for k, v in pairs(ActivePosters) do
>             if #(GLOBAL_COORDS - v.pointA) < Config.ViewDistance or #(GLOBAL_COORDS - v.pointB) < Config.ViewDistance then
>                 sleep = 0
>                 DrawImageOnArea(v.pointA, v.pointB, v.pointB.z, v.pointA.z, 255, 255, 255, 255, v.textureid, v.txn)
>             end
>         end
>         Wait(sleep)
>     end
> end)

All you have to do is change the value of "config.viewdistance" and don't forget to add "config.lua" to the fxmanifest and all good ^^

**Comment by Xilophinum** [comment]
Added Render Distance Config Option
